version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: kacifyapi
    env_file:
      - fileName: ./api/.env
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kacifyfrontend
    depends_on:
      - api
    env_file:
      - fileName: ./frontend/.env