version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: kacifyapi
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kacifyfrontend
    depends_on:
      - api
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
  mongodb:
    image: mongo:latest
    container_name: kacifymongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db:rw