name: CD workflow

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: git pull
        working-directory: /Users/rahul/Documents/kacify

      - name: Docker build frontend
        run: docker build -t kacify-frontend .
        working-directory: /Users/rahul/Documents/kacify/frontend

      - name: Docker build API
        run: docker build -t kacify-api .
        working-directory: /Users/rahul/Documents/kacify/api

      - name: Start the app
        run: bash start.sh
        working-directory: /Users/rahul/Documents/kacify