name: CD workflow

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: git pull
        working-directory: /Users/rahul/Documents/kacify

      - name: Docker build frontend
        run: docker build -t kacifyfrontend .
        working-directory: /Users/rahul/Documents/kacify/frontend

      - name: Docker build API
        run: docker build -t kacifyapi .
        working-directory: /Users/rahul/Documents/kacify/api

      - name: Start docker
        run: docker-compose up -d
        working-directory: /Users/rahul/Documents/kacify