name: CD workflow

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: git pull
        working-directory: ~/kacify

      - name: Docker build frontend
        run: cd frontend && docker build -t kacifyfrontend .
        working-directory: ~/kacify/frontend

      - name: Docker build API
        run: cd api && docker build -t kacifyapi .
        working-directory: ~/kacify/api

      - name: Start docker
        run: docker-compose up -d
        working-directory: ~/kacify