name: ci-cd

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: self-hosted

    steps:
      - name: main
        run: |
          cd ~/kacify
          git pull origin main
          cd ~/kacify/api
          npm run build
          pm2 stop mernApi
          pm2 start npm --name "mernApi" -- start
          cd ~/kacify/frontend
          pm2 stop mernFrontend
          pm2 start npm --name "mernFrontend" -- start