name: CI workflow

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker build frontend
        run: cd frontend && docker build -t kacify-frontend .

      - name: Docker build API
        run: cd api && docker build -t kacify-api .